project:
  type: book

book:
  title: "casa0023_learning_diary"
  author: "Zachary Pescod-Everiss"
  date: "1/26/2023"
  chapters:
    - index.qmd
    - 01_Intro.qmd
    - 02_Presentation.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

