project:
  type: book

book:
  title: "casa0023_learning_diary"
  author: "Zachary Pescod-Everiss"
  date: "2/13/2023"
  chapters:
    - index.qmd
    - 01_Intro.qmd
    - 02_Presentation.qmd
    - 03_Corrections.qmd
    - 04_policy.qmd
    - 05_GEE.qmd
    - 06_classificaiton1.qmd
    - 07_classification2.qmd
    - 08_Temperature.qmd
    - glossary.qmd
    - references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

